#!/bin/bash
clear
list=()
list1=()

ans=(${list[*]})
ans1=(${list1[*]})
len=${#ans[*]}
GREEN='\033[1;32m'
RED='\033[1;31m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
MAG='\033[1;36m'
NC='\033[0m'
for (( ; ;))
do

search(){
read -p "$(echo -e ${GREEN}Search a name:${NC})" nam
grep $nam gg
if [[ ${ans[*]} =~ $nam ]];then
  echo -e "${BLUE}Contact found${NC}"
else
  echo -e "${BLUE}Contact does not exist${NC}"
fi
> gk
> gg
}


update(){
read -p "$(echo -e ${GREEN}Enter the name whose number is to be updated:${NC})" na
grep $na gg
for (( j=0; j<$len; j++ ))
do
   if [[ ${ans[j]} =~ $na ]];then
     for (( ; ; ));do
      read -p "$(echo -e ${GREEN}Enter the new number:${NC})" num
      if ! [[ "$num" =~ ^[0-9]+$ ]];then
        echo -e "${BLUE}Sorry integers only${NC}"
      else
        ans1[j]=$num
        break
      fi
     done
   elif [[ ${ans1[j]} =~ $na ]];then
    for (( ; ; ));do
      read -p "$(echo -e ${GREEN}Enter the new number:${NC})" num
      if ! [[ "$num" =~ ^[0-9]+$ ]];then
        echo -e "${BLUE}Sorry integers only${NC}"
      else
        ans1[j]=$num
        break
      fi
     done
   fi
> gk
> gg
done
echo -e "${BLUE}Number is updated Successfully${NC}"
}


delete(){
read -p "$(echo -e ${GREEN}Enter your contact to be deleted:${NC})" numb
      sed -i -e "/$numb/d" gg

> gk
> gg

echo -e "${BLUE}Number is deleted successfully${NC}"
}

quit(){
exit
}

create(){
read -p "$(echo -e ${GREEN}Enter your name:${NC})" name
read -p "$(echo -e ${GREEN}Enter your contact number:${NC})" number
ans+=("$name,")
ans1+=("$number")

  len=$(( len+1 ))
  echo -e "${BLUE}Contact is created successfully${NC}"

}

display(){
for (( l=0; l<$len; l++ ))
do 
   > contacts
   echo -e "${MAG}${ans[l]} ${ans1[l]}${NC}" >> gk
done
column gk -t -s "," >> gg  
sort -k 1 gg >> contacts
cat contacts
> gk
> gg
}



echo "=============================================================="
echo -e  "${YELLOW}1.Display all the contacts${NC}"
echo -e  "${YELLOW}2.Add the contact${NC}"
echo -e  "${YELLOW}3.Search the contact${NC}"
echo -e  "${YELLOW}4.Update the contact${NC}"
echo -e  "${YELLOW}5.Delete the contact${NC}"
echo -e  "${YELLOW}6.Quit${NC}"

echo "==============================================================="
read -p "$(echo -e ${RED}Enter the choice:${NC})" choice
echo "==============================================================="

if [[ $choice = "1" ]];then
    display
elif [[ $choice = "2" ]];then
      create
elif [[ $choice = "3" ]];then
     search
elif [[ $choice = "4" ]];then
     update
elif [[ $choice = "5" ]];then
     delete
elif [[ $choice = "6" ]];then
     quit
else
   echo "You have entered wrong choice"
  > gk
 > gg
fi
done
